// Shared trust profile v2 (epochs) conformance vector, format
// `dnsid-c2sp-trust-profile-epochs@v1`. The fixture is a byte-for-byte copy of
// dnsid-go log/c2sptlog/testdata/c2sp-trust-profile-epochs-v1.json, generated by
// dnsid-go log/c2sptlog/trust_epoch_vectors_gen_test.go (see
// fixtures/c2sp-trust-profile-epochs.md). Do not edit it here; re-copy it from
// dnsid-go and update FIXTURE_SHA256 and the case count. Every key in it is a
// disposable test key.
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import type { DnsIdJWK } from '@dnsid-ai/protocol';
import {
  C2spTlogError,
  InMemoryTrustedC2spCheckpointStore,
  advanceTrustedC2spCheckpoint,
  c2spTlogTrustEpochs,
  c2spTlogTrustProfilePolicy,
  createC2spTlogVerificationRegistry,
  enforceCheckpointPolicy,
  parseC2spTlogLr,
  parseC2spTlogTrustProfile,
  parseCheckpoint,
  requiredC2spResourceFetchGuarantees,
  verifyC2spStreamBundle,
  type C2spBoundedResourceFetcher,
  type C2spTlogReader,
} from '@dnsid-ai/log-c2sp-tlog';

const FIXTURE_URL = new URL('./fixtures/c2sp-trust-profile-epochs-v1.json', import.meta.url);
/** sha256 of dnsid-go a52596f3bdc5132f8b6f37ddf77836a5e9133921:log/c2sptlog/testdata/c2sp-trust-profile-epochs-v1.json */
const FIXTURE_SHA256 = '9ee8e63a394aaa3abc55c6c0900783a444ac8ab259032a08db828ebf1abb5fdf';
const FIXTURE_BYTES = readFileSync(FIXTURE_URL);

type Expect = { result: 'accept' | 'reject'; reason?: string; epoch?: string };
interface Vectors {
  format: string;
  reason_codes: Record<string, string>;
  parameters: {
    scope: string;
    log_prefix: string;
    origin: string;
    lr: string;
    fqdn: string;
    now: number;
    checkpoint_max_age_seconds: number;
    max_bundle_lifetime_seconds: number;
    clock_skew_seconds: number;
  };
  tree: { entries: string[] };
  profiles: Record<string, string>;
  profile_cases: Array<{ name: string; document: string; expect: Expect; epoch_ids?: string[] }>;
  checkpoint_cases: Array<{ name: string; profile: string; checkpoint: string; tree_size: number; expect: Expect }>;
  bundle_cases: Array<{ name: string; profile: string; bundle: string; expect: Expect }>;
  continuity_cases: Array<{
    name: string;
    profile: string;
    steps: Array<{ checkpoint: string; consistency_proof: string[]; expect: Expect; trusted_after: { tree_size: number; root_hash: string } | null }>;
  }>;
}

const vectors = JSON.parse(FIXTURE_BYTES.toString('utf8')) as Vectors;
const p = vectors.parameters;
const nowMs = p.now * 1000;
const maxAgeMs = p.checkpoint_max_age_seconds * 1000;
const skewMs = p.clock_skew_seconds * 1000;
const reference = parseC2spTlogLr(p.lr);
const utf8 = (text: string) => new TextEncoder().encode(text);

/**
 * Maps an SDK error to the vector's language-neutral reason code. The codes,
 * not the messages, are the cross-SDK contract. Errors wrapped at the reader
 * boundary are matched through their cause chain.
 */
function reasonOf(error: unknown): string {
  const messages: string[] = [];
  for (let current = error; current instanceof Error; current = (current as Error & { cause?: unknown }).cause) messages.push(current.message);
  const text = messages.join(' <- ');
  for (const [code, pattern] of [
    ['bundle_signer', /signer is not accepted|signature key is not uniquely trusted/],
    ['policy_hash', /policy_hash mismatch/],
    ['max_tree_size', /is above trust epoch/],
    ['min_tree_size', /is below trust epoch/],
    ['witness_quorum', /witness quorum not satisfied/],
    ['stale', /checkpoint is stale|checkpoint is too stale/],
    ['log_signature', /missing accepted log signature/],
    ['rollback', /rollback detected/],
    ['root_conflict', /equal-size C2SP checkpoint has a different root/],
    ['consistency_failed', /invalid C2SP checkpoint consistency proof/],
  ] as const) {
    if (pattern.test(text)) return code;
  }
  return `unclassified: ${text}`;
}

function expectOutcome(expected: Expect, outcome: { error?: unknown; epoch?: string }): void {
  if (expected.result === 'accept') {
    expect(outcome.error === undefined ? 'accept' : `reject ${reasonOf(outcome.error)}`).toBe('accept');
    expect(outcome.epoch).toBe(expected.epoch);
  } else {
    expect(outcome.error === undefined ? 'accept' : reasonOf(outcome.error)).toBe(expected.reason);
  }
}

function profile(name: string) {
  const document = vectors.profiles[name];
  if (document === undefined) throw new Error(`unknown vector profile ${name}`);
  return parseC2spTlogTrustProfile(utf8(document));
}

/** Verifies a bare checkpoint exactly as the registry's reader policy does, with the vector's freshness. */
function verifyCheckpoint(profileName: string, checkpointText: string) {
  const checkpoint = parseCheckpoint(checkpointText);
  const result = enforceCheckpointPolicy(checkpoint, reference.origin, c2spTlogTrustProfilePolicy(profile(profileName)), reference.scope, nowMs, skewMs, {
    maxCheckpointAgeMs: maxAgeMs,
  });
  return { checkpoint, result };
}

function decodedEntry(index: number): Record<string, unknown> {
  return JSON.parse(Buffer.from(vectors.tree.entries[index]!, 'base64').toString('utf8')) as Record<string, unknown>;
}

// The stream's public keys: the entity key from ISSUANCE and the current
// operational key from the KEY_ROTATION that the bundles carry.
const entityKey = decodedEntry(0).ek as DnsIdJWK;
const currentOperationalKey = decodedEntry(1).new_ku as DnsIdJWK;

/** A bounded fetcher that serves only this bundle at the reader's bundle endpoint. */
function bundleFetcher(bundle: string): C2spBoundedResourceFetcher {
  const endpoint = `${p.log_prefix}/streams/${encodeURIComponent(p.fqdn)}?format=bundle`;
  return {
    securityGuarantees: requiredC2spResourceFetchGuarantees,
    async fetchBounded(url: string) {
      if (url === endpoint) return utf8(bundle);
      throw new C2spTlogError(`unexpected vector fetch ${url}`, { status: 404 });
    },
  };
}

describe('C2SP trust profile v2 (epochs) shared vectors', () => {
  beforeEach(() => {
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(nowMs);
  });
  afterEach(() => {
    vi.useRealTimers();
  });

  it('is the byte-for-byte dnsid-go fixture with full coverage', () => {
    expect(createHash('sha256').update(FIXTURE_BYTES).digest('hex')).toBe(FIXTURE_SHA256);
    expect(vectors.format).toBe('dnsid-c2sp-trust-profile-epochs@v1');
    const cases = vectors.profile_cases.length + vectors.checkpoint_cases.length + vectors.bundle_cases.length + vectors.continuity_cases.length;
    expect(cases).toBe(79);
    const reasons = [
      ...vectors.profile_cases, ...vectors.checkpoint_cases, ...vectors.bundle_cases,
      ...vectors.continuity_cases.flatMap(testCase => testCase.steps),
    ].flatMap(testCase => testCase.expect.reason === undefined ? [] : [testCase.expect.reason]);
    expect(new Set(reasons)).toEqual(new Set(Object.keys(vectors.reason_codes)));
  });

  describe('profile cases', () => {
    it.each(vectors.profile_cases.map(testCase => [testCase.name, testCase] as const))('%s', (_name, testCase) => {
      let parsed: ReturnType<typeof parseC2spTlogTrustProfile> | undefined;
      let error: unknown;
      try {
        parsed = parseC2spTlogTrustProfile(utf8(testCase.document));
      } catch (cause) {
        error = cause;
      }
      if (testCase.expect.result === 'reject') {
        expect(testCase.expect.reason).toBe('profile_invalid');
        expect(error).toBeInstanceOf(Error);
        return;
      }
      expect(error).toBeUndefined();
      expect(c2spTlogTrustEpochs(parsed!).map(epoch => epoch.id)).toEqual(testCase.epoch_ids);
    });
  });

  describe('checkpoint cases', () => {
    it.each(vectors.checkpoint_cases.map(testCase => [testCase.name, testCase] as const))('%s', (_name, testCase) => {
      let outcome: { error?: unknown; epoch?: string };
      try {
        const { checkpoint, result } = verifyCheckpoint(testCase.profile, testCase.checkpoint);
        expect(checkpoint.treeSize).toBe(testCase.tree_size);
        outcome = { epoch: result.trustEpoch };
      } catch (error) {
        outcome = { error };
      }
      expectOutcome(testCase.expect, outcome);
    });
  });

  describe('bundle cases', () => {
    it.each(vectors.bundle_cases.map(testCase => [testCase.name, testCase] as const))('%s: verifyC2spStreamBundle', async (_name, testCase) => {
      const trust = profile(testCase.profile);
      const trustOptions = trust.version === 1
        ? { policyBytes: trust.policyDocument, bundleKeys: trust.bundleVerifierKeys }
        : { trustEpochs: c2spTlogTrustEpochs(trust) };
      let outcome: { error?: unknown; epoch?: string };
      try {
        const verified = await verifyC2spStreamBundle(utf8(testCase.bundle), {
          ...trustOptions,
          expectedFqdn: p.fqdn,
          expectedLogReference: p.lr,
          entityKey,
          maxBundleBytes: 8 * 1024 * 1024,
          maxEvents: 10_000,
          maxBundleLifetimeMs: p.max_bundle_lifetime_seconds * 1000,
          checkpointFreshnessMs: maxAgeMs,
          maxClockSkewMs: skewMs,
          nowMs,
          trustedCheckpointStore: new InMemoryTrustedC2spCheckpointStore(),
        });
        outcome = { epoch: verified.trustEpoch };
      } catch (error) {
        outcome = { error };
      }
      expectOutcome(testCase.expect, outcome);
    });

    it.each(vectors.bundle_cases.map(testCase => [testCase.name, testCase] as const))('%s: verification registry', async (_name, testCase) => {
      // The full product path: trust profile -> registry -> reader -> bundle fetch -> verification.
      const registry = await createC2spTlogVerificationRegistry({
        trustProfile: profile(testCase.profile),
        resourceFetcher: bundleFetcher(testCase.bundle),
        checkpointMaxAge: maxAgeMs,
        maxBundleLifetimeMs: p.max_bundle_lifetime_seconds * 1000,
        allowedClockSkew: skewMs,
        requireStreamBundle: true,
      });
      const reader = registry.newReader(p.lr) as C2spTlogReader;
      let error: unknown;
      try {
        await reader.verifyBilateralBinding({ fqdn: p.fqdn, gi: decodedEntry(0).gi }, entityKey, currentOperationalKey);
      } catch (cause) {
        error = cause;
      }
      if (testCase.expect.result === 'accept') expect(error === undefined ? 'accept' : `reject ${reasonOf(error)}`).toBe('accept');
      else expect(error === undefined ? 'accept' : reasonOf(error)).toBe(testCase.expect.reason);
    });
  });

  describe('continuity cases', () => {
    it.each(vectors.continuity_cases.map(testCase => [testCase.name, testCase] as const))('%s', async (_name, testCase) => {
      const store = new InMemoryTrustedC2spCheckpointStore();
      for (const step of testCase.steps) {
        let outcome: { error?: unknown; epoch?: string };
        try {
          const { checkpoint, result } = verifyCheckpoint(testCase.profile, step.checkpoint);
          await advanceTrustedC2spCheckpoint(store, reference, checkpoint, result.checkpointWitnessTime!, {
            consistencyProofSource: {
              async fetchConsistencyProof() {
                return step.consistency_proof.map(node => new Uint8Array(Buffer.from(node, 'base64')));
              },
            },
          });
          outcome = { epoch: result.trustEpoch };
        } catch (error) {
          outcome = { error };
        }
        expectOutcome(step.expect, outcome);
        const trusted = await store.load(reference.origin);
        if (step.trusted_after === null) {
          expect(trusted).toBeUndefined();
        } else {
          expect(trusted && { tree_size: trusted.treeSize, root_hash: Buffer.from(trusted.rootHash).toString('base64') }).toEqual(step.trusted_after);
        }
      }
    });
  });
});
